spring:
  datasource:
    url: jdbc:sqlite:d:/test.db
    driver-class-name: org.sqlite.JDBC


mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'

server:
  port: 8087